pets_home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from base.views import home, adocao, animal_detalhes, busca_site, sobre_nos, como_ajudar, blog, confirmacao_cadastro_adocao

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='inicio'),
    path('adocao/', adocao, name='adocao'),
    path('animal_detalhes/<int:animal_id>/', animal_detalhes, name='animal_detalhes'),
    path('busca/', busca_site, name='busca_site'),
    path('sobre-nos/', sobre_nos, name='sobre_nos'),
    path('como-ajudar/', como_ajudar, name='como_ajudar'),
    path('blog/', blog, name='blog'),
    path('confirmacao/', confirmacao_cadastro_adocao, name='confirm_adocao'),
    path('api-auth/', include('rest_framework.urls')),
    path('apipets/', include('rest_api.urls', namespace='apipets'))
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest_api/urls.py
from django.urls import path
from rest_api.views import api_pets

app_name = 'rest_api'
urlpatterns = [
  path('api_pets', api_pets, name='api_pets'),
]

animais/models.py
from django.db import models

# Create your models here.


class Animal(models.Model):
    GENEROS_ANIMAIS = (
        ('F', 'Fêmea'),
        ('M', 'Macho')
    )
    nome = models.CharField(max_length=55)
    genero = models.CharField(
        max_length=50, choices=GENEROS_ANIMAIS, null=True)
    especie = models.CharField(max_length=50)
    idade = models.PositiveIntegerField()
    peso = models.PositiveIntegerField(null=True)
    raca = models.CharField(max_length=50)
    historico_saude = models.TextField()
    imagem = models.ImageField(upload_to='imagens/', blank=True, null=True)

    def __str__(self):
        return f'{self.nome} - {self.especie} : {self.idade}'

    class Meta:
        verbose_name = 'Cadastro de Animal'
        verbose_name_plural = 'Cadastros de Animais'
        ordering = ['-idade']

base/models.py
from django.db import models
from animais.models import Animal

# Create your models here.


class AnimalAdocao(models.Model):
    animal = models.ForeignKey(
        Animal, on_delete=models.CASCADE, null=True, blank=True)
    nome = models.CharField(max_length=51)
    email = models.EmailField(max_length=77)
    cpf = models.CharField(max_length=11)
    dataNascimento = models.DateField()
    telefone = models.CharField(max_length=16)
    profissao = models.CharField(max_length=100)
    cep = models.CharField(max_length=8)
    endereco = models.CharField(max_length=255)
    cidade = models.CharField(max_length=102)
    estado = models.CharField(max_length=2)
    motivoAdocao = models.TextField()
    emCasoDeViagem = models.TextField()
    experienciaAnterior = models.TextField()
    temAnimal = models.BooleanField(
        choices=[(True, 'Sim'), (False, 'Não')], default=False)
    status = models.CharField(max_length=22, choices=[('Pendente', 'Pendente'), (
        'Aprovada', 'Aprovada'), ('Recusada', 'Recusada')], default='Pendente')
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.nome} [{self.cpf}]'

    class Meta:
        verbose_name = 'Formulário de Adoção'
        verbose_name_plural = 'Formulários de Adoções'
        ordering = ['-data']

base/forms.py
from django import forms
from django.core.exceptions import ValidationError
from base.models import AnimalAdocao


class AnimalForm(forms.ModelForm):
    ESTADOS_CHOICES = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )

    class Meta:
        model = AnimalAdocao
        exclude = ['data', 'animal', 'status']
    animal = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    nome = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Nome Completo'}),)
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'placeholder': ''}),)
    cpf = forms.CharField(max_length=11, label='CPF', widget=forms.TextInput(
        attrs={'placeholder': 'Apenas números'}),)
    dataNascimento = forms.DateField(label='Data de Nascimento', widget=forms.DateInput(
        attrs={'placeholder': 'DD/MM/YYYY'}), input_formats=['%d/%m/%Y'],)
    telefone = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': ''}),)
    profissao = forms.CharField(
        label='Profissão', widget=forms.TextInput(attrs={'placeholder': ''}),)
    cep = forms.CharField(max_length=8, widget=forms.TextInput(
        attrs={'placeholder': 'Apenas números'}),)
    endereco = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Rua, nº, complemento'}),)
    cidade = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': ''}),)
    estado = forms.ChoiceField(choices=ESTADOS_CHOICES)
    motivoAdocao = forms.CharField(label='Motivo da Adoção', widget=forms.Textarea(
        attrs={'placeholder': '', 'rows': '3'}),)
    emCasoDeViagem = forms.CharField(
        label='Em caso de viagem, onde você deixará o animal adotado?', widget=forms.TextInput(attrs={'placeholder': ''}),)
    experienciaAnterior = forms.CharField(label='Experiência Anterior com Animais de Estimação', widget=forms.Textarea(
        attrs={'placeholder': '', 'rows': '2'}),)
    temAnimal = forms.ChoiceField(label='Tem algum animal em sua residência?', choices=[
                                  (True, 'Sim'), (False, 'Não')], widget=forms.RadioSelect)

    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf')
        if len(cpf) != 11 or not cpf.isdigit():
            raise ValidationError(
                "CPF inválido. Certifique-se de inserir apenas números e ter 11 dígitos.")

        return cpf

    def clean_dataNascimento(self):
        data_nascimento = self.cleaned_data.get('dataNascimento')
        if data_nascimento.year < 1900:
            raise ValidationError(
                "Ano de nascimento inválido. Certifique-se de inserir uma data válida.")

        return data_nascimento

    def clean_cep(self):
        cep = self.cleaned_data.get('cep')
        if len(cep) != 8 or not cep.isdigit():
            raise ValidationError("O CEP deve ter 8 dígitos e apenas números")
        return cep

    def clean_telefone(self):
        telefone = self.cleaned_data.get('telefone')
        if not telefone.isdigit():
            raise ValidationError("O telefone deve conter apenas números")
        return telefone

    def clean(self):
        cleaned_data = super().clean()

        return cleaned_data

base/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, reverse
from base.forms import AnimalForm
from base.models import AnimalAdocao
from animais.models import Animal
from animais.filters import AnimalFilter


def home(request):
    animais = Animal.objects.all()[:4]
    return render(request, 'home.html', {'animais': animais})


def adocao(request):
    animais = Animal.objects.all()
    return render(request, 'adocao.html', {'animais': animais})


def animal_detalhes(request, animal_id):
    animal = get_object_or_404(Animal, pk=animal_id)

    contexto = {
        'sucesso': False,
        'animal': animal,
    }

    if request.method == 'POST':
        form = AnimalForm(request.POST)
        if form.is_valid():
            animal_inst = Animal.objects.get(pk=animal_id)
            form.cleaned_data['animal'] = animal_inst
            AnimalAdocao.objects.create(**form.cleaned_data)
            contexto['sucesso'] = True
            return HttpResponseRedirect(reverse('confirm_adocao'))
        else:
            contexto['erro'] = True
            contexto['form'] = form
    else:
        form = AnimalForm(initial={'animal': animal_id})
        contexto['form'] = form
    return render(request, 'animal.html', contexto)


def confirmacao_cadastro_adocao(request):
    return render(request, 'confirmacao_cadastro_adocao.html')


def busca_site(request):
    query = request.GET.get('q')
    has_results = False
    animal_filter = None

    if query:
        animal_filter = AnimalFilter(
            data={'search': query}, queryset=Animal.objects.all())
        has_results = animal_filter.qs.exists()

    return render(request, 'busca_resultados.html', {'filter': animal_filter, 'has_results': has_results})


def como_ajudar(request):
    return render(request, 'como_ajudar.html')


def blog(request):
    return render(request, 'blog.html')


def sobre_nos(request):
    return render(request, 'sobre_nos.html')

base/templates/adocao.html
{% extends "layout.html" %}
{% load bootstrap5 %}
{% load static %}
{% block content %}

<h1 class="text-center">Adote!</h1>
<h3>Nossos Animais</h3>
<p>
  Descubra o seu futuro companheiro entre os animais listados abaixo. Clique no
  botão 'Quero Adotar' para obter detalhes adicionais e preencher nosso
  formulário de adoção
</p>
<div class="row">
  {% for animal in animais %}
  <div class="mb-4 mt-4 col-lg-3 col-md-6 col-sm-12 d-flex justify-content-center">
    <div class="card mt-2 card-adocao" style="width: 12rem">
      <a href="{% url 'animal_detalhes' animal.id %}">
        <img src="{{ animal.imagem.url }}" class="card-img-top" alt="animal" />
      </a>
      <div class="card-body">
        <h3 class="h5 card-title text-center">{{ animal.nome }}</h3>
        <p class="small card-text text-center">
          <strong>Idade:</strong> {{ animal.idade }} anos<br />
          <a href="{% url 'animal_detalhes' animal.id %}" class="mt-1 btn-adocao btn btn-primary btn-sm px-2">Quero
            adotar
          </a>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

base/templates/animal.html
{% extends "layout.html" %} 
{% load bootstrap5 %} 

{% block content %}
{% if erro %}
<div class="row">
  <div class="mt-3 col-md-8 col-12 mx-auto">
    <div class="alert alert-danger">
      <strong>Erro no formulário:</strong>
      <ul>
        {% for field, errors in form.errors.items %}
          {% for error in errors %}
            <li>{{ field }}: {{ errors|join:", " }}</li>
          {% endfor %}
        {% endfor %}  
      </ul>
    </div>
  </div>
</div>
{% endif %}
<div class="row">
  <div class="col-md-10 col-12 mx-auto d-flex justify-content-center">
    <div class="card mt-2 card-adocao" style="width: 22rem">
      <img
        src="{{ animal.imagem.url }}"
        class="card-img-top img-thumbnail"
        alt="animal para adoção"
        style="width: 100%; height: auto;"
      />
      <div class="card-body">
        <h3 class="h5 card-title text-center">{{ animal.nome }}</h3>
        <p class="card-text">
          <strong>Espécie:</strong> {{ animal.especie }}<br />
          <strong>Idade:</strong> {{ animal.idade }} anos<br />
          <strong>Raça:</strong> {{ animal.raca }}<br />
          <strong>Gênero:</strong> {{ animal.get_genero_display }}<br />
          <strong>Histórico de Saúde:</strong> {{ animal.historico_saude }}
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
<div class="col-md-8 col-12 mx-auto">
<div class="card mt-4">
  <div class="card-body">
    <h1 class="text-body-emphasis text-center">Formulário de Adoção</h1>
    <form action="" method="POST" id="form" class="small-form">
      {% csrf_token %} 
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-cadastro btn-primary btn-block">
        Finalizar cadastro
      </button>
    </form>
  </div>
</div>
</div>
</div>
{% endblock %}

base/templates/blog.html
{% extends "layout.html" %} 
{% load bootstrap5 %} 
{% load static %} 
{% block content %}
<main class="container-fluid">
  <h1 class="text-center">Blog</h1>
  <div class="text-center mt-3">
    <h3>A Relação entre Animais de Estimação e Saúde Mental:</h3>
    <p>Como os animais podem melhorar a saúde mental.</p>
    <img
    src="{% static 'images/IMG_3192.jpg' %}"
    class="img-thumbnail mt-3 mb-4"
    style="width: 450px;"
    alt="cachorro-feliz"
    />
  </div>
  <hr>
  <div class="text-center row mt-3">
    <h3>Enriquecimento ambiental: o que é e como fazer para cães e gatos</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ratione enim dolore quidem est eius maiores at! Quibusdam voluptatum, natus nesciunt aspernatur iure dicta numquam soluta ullam ipsa necessitatibus quasi?</p>
    <img
      src="{% static 'images/home-Cute-Dog.jpg' %}"
      class="img-thumbnail"
      alt="cachorro-muito-fofo"
    />
  </div>
  <hr>
  <div class=" text-center row mt-4">
    <h2 class="text-center mb-4">Finais Felizes</h2>
    <img
      src="{% static 'images/3-1627065210.jpeg' %}"
      class="img-fluid img-thumbnail mt-3 mb-4"
      alt="cachorro deitado"
    />
  </div>
  <h4 class="text-center mt-5 mb-5">
    Juntos, estamos construindo pontes de amor que conectam corações humanos a
    patinhas peludas, transformando vidas de ambos os lados.
  </h4>
</main>
{% endblock %}

base/templates/busca_resultados.html
{% extends "layout.html" %} 
{% load bootstrap5 %} 
{% load static %}

<main class="container">
  {% block content %}
  <h1 class="text-center">Resultados da busca</h1>

  {% if has_results %}
  <div class="row row-cols-1 row-cols-md-4 row-cols-lg-3 g-4 mt-4">
    {% for animal in filter.qs %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 16rem">
        <a href="{% url 'animal_detalhes' animal.id %}" class="card-img-top">
          <img
            src="{{ animal.imagem.url }}"
            class="img-fluid img-thumbnail"
            alt="animais"
          />
        </a>
        <div class="card-body text-center">
          <h3 class="h5 card-title text-center">{{ animal.nome }}</h3>
          <p>{{ animal.especie }}</p>
          <a
            href="{% url 'animal_detalhes' animal.id %}"
            class="mt-1 btn-adocao btn btn-primary btn-sm px-2"
            >Quero adotar</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="container-fluid text-center mt-5">
    <div class="row justify-content-center">
      <h5>Ops! Não conseguimos localizar sua pesquisa.</h5>
    </div>
    <img
      src="{% static 'images/noresults.jpg' %}"
      alt="sem-resultado"
      style="width: 350px; max-height: 100%"
    />
    <div class="mt-4 mb-5">
      <a href="{% url 'inicio' %}" class="btn btn-success">Voltar para home</a>
    </div>
  </div>
  {% endif %} 
  {% endblock %}
</main>

base/templates/como_ajudar.html
{% extends "layout.html" %}
{% load bootstrap5 %}
{% load static %} 

{% block content %}
<main class="container">
<h1 class="text-center">Doações</h1>
<div class="row mt-4">
<h3>Precisamos de sua ajuda!</h3>
<div class="mt-2 col-lg-6 col-sm-12">
<p>Sua ajuda faz toda diferença na vida desses animais especiais. Na Pet's Home, acreditamos que cada pequeno gesto faz uma grande diferença na vida desses amigos peludos que tanto precisam de amor e cuidado.</p>
</div>
<div class="col-lg-6 col-sm-12 d-flex justify-content-center">
  <img
    src="{% static 'images/cachorro-em-abrigo-com-voluntario.jpg' %}"
    class="img-doacao img-thumbnail"
    alt="cachorro com voluntario"
  />
</div>
</div>
<div class="row text-center mt-5">
<h5 class="mb-4">Aqui estão algumas maneiras pelas quais você pode se envolver e fazer parte da mudança:</h5>
<div class="col-md-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Seja um Voluntário</h5>
      <p class="card-text">Junte-se à nossa equipe de voluntários apaixonados e compartilhe seu tempo e carinho diretamente com nossos animais.</p>
      <button class="btn btn-success">Ser Voluntário</button>
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Doações São Bem-Vindas</h5>
      <p class="card-text">Seja uma contribuição única ou uma doação mensal, cada valor doado nos ajuda a oferecer cuidados adequados.</p>
      <button class="btn btn-success">Doação</button>
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Participe de Eventos</h5>
      <p class="card-text">Esteja atento aos eventos promovidos pelo abrigo, como feiras de adoção e palestras educacionais.</p>
      <button class="btn btn-success">Calendário</button>
    </div>
  </div>
</div>
</div>
<h4 class="text-center mt-5 mb-5">
  Juntos, estamos construindo pontes de amor que conectam corações humanos a
  patinhas peludas, transformando vidas de ambos os lados.
</h4>
</main>
{% endblock %}

base/templates/confirmacao_cadastro_adocao.html
{% extends "layout.html" %} 
{% load bootstrap5 %} 
{% load static %}

<main class="container-fluid">
  {% block content %}
  <div class="col-md-9 mx-auto text-center">
    <div class="mb-4">
  <h2 class="mb-3">Parabéns! Seu cadastro foi realizado com sucesso!</h2>
      <h5>Agora é só aguardar. Em breve, você receberá um e-mail contendo detalhes sobre a aprovação do seu pedido de adoção.</h5> 
    </div>
      <img
      src="{% static 'images/IMG_3192.jpg' %}"
      class="img-thumbnail"
      alt="cachorro-sorrindo"
      style="width: 340px; max-width: 100%"
    />
  </div>
  <div class="mt-4 mb-5 text-center">  
      <a href="{% url 'inicio' %}" class="btn btn-success">Voltar para home</a>
  </div>    
  {% endblock %}
</main>

base/templates/home.html
{% extends "layout.html" %} 
{% load bootstrap5 %} 
{% load static %}

<main class="container">
  {% block content %}
  <h1>A Pet's Home</h1>
  <div class="justify-content-center mt-3">
  <p>
    Bem-vindo à Pet's Home, o lar amoroso para animais que aguardam ansiosamente
    por uma família. Somos uma associação dedicada a cuidar
    e proteger animais desabrigados, oferecendo-lhes amor, cuidado e esperança.
    Nossa missão é encontrar lares adotivos para esses animais especiais,
    proporcionando alegria e carinho tanto para eles quanto para suas novas
    famílias. Explore nosso site e descubra como você pode fazer a diferença.
  </p>
  </div>
  <div class="text-center mt-4">
    <h4>Encontre seu companheiro perfeito entre os animais adoráveis que aguardam ansiosamente por um lar para chamar de seu.</h4>
  </div>
  <h2 class="mt-5 text-center">Adote</h2>
  <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 m-2">
    {% for animal in animais %}
    <div class="mb-4 mt-3 d-flex justify-content-center">
      <a href="{% url 'animal_detalhes' animal.id %}">
      <img
        src="{{ animal.imagem.url}}"
        class="img-home img-fluid"
        alt="animais"
      />
      </a>
    </div>
    {% endfor %}
  </div>
  <div class="d-flex justify-content-center mb-5">
    <a href="{% url 'adocao' %}" class="btn btn-home btn-success px-5 mb-4">Ver Mais</a>
  </div>
  <div class="row mt-5 mb-4">
    <div class="col-md-6 mb-4">
      <img
        src="{% static 'images/home-Cute-Dog.jpg' %}"
        class="img-thumbnail"
        alt="cachorro-muito-fofo"
      />
    </div>
    <div class="col-md-6 mb-4">
    <h3>Nosso Compromisso: Cuidar, Proteger, Amar.</h3>
    <p>Garantimos que cada animal receba os cuidados necessários, incluindo vacinas, cuidados veterinários e muito, muito carinho. Junte-se a nós na promoção do bem-estar animal!</p>
      <a href="{% url 'sobre_nos' %}" class="btn btn-success">Saiba Mais</a>
  </div>
  <div class="col-md-6 mb-4">
    <img
      src="{% static 'images/dog-home.jpg' %}"
      class="img-thumbnail"
      alt="cachorro-fofo"
    />
  </div>
  <div class="col-md-6">
  <h3>Faça a Diferença.</h3>
  <p>Contribua para Pet's Home. Sua doação ajuda a garantir que possamos continuar fornecendo amor, cuidados e esperança a animais necessitados. Saiba como se tornar um parceiro na causa do bem-estar animal.</p>
  <a href="{% url 'como_ajudar' %}" class="btn btn-success">Como ajudar</a>
</div>
  </div>
  <h4 class="text-center mt-5 mb-5">
    Juntos, estamos construindo pontes de amor que conectam corações humanos a
    patinhas peludas, transformando vidas de ambos os lados.
  </h4>
  {% endblock %}
</main>

base/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="auto">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet's Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="/static/bootstrap.min.css" rel="stylesheet" type="text/css">

  <!--Bootstrap  JavaScript-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>

  <!--Bootstrap  JavaScript Bundle-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</head>
<body>
  <main class="container">
    {% include "nav.html" %}
    {% block content %} 
    {% endblock %}
  </main>
  <footer class="footer-color d-flex align-items-end mt-4">
    <div class="container">
      <div class="itens-footer row d-flex align-items-baseline">
        <div class="col text-center align-self-center">
          <a href="{% url 'inicio' %}">
          <img class="img-footer" src="{% static 'images//logo-petsh.svg' %}" alt="logo">
          </a>
        </div>
        <div class="col-md-8 text-center">
          <div class="footer-section">
            <h5 class="mb-2">Contatos</h5>
            <a href="tel:+551111111111">
              <h6><i class="bi bi-telephone-fill m-2"></i>+55 (21) 1111-1111</h6>
            </a>
            <a href="mailto:info@petshome.com">
              <h6><i class="bi bi-envelope-fill m-2"></i>info@petshome.com</h6>
            </a>
          <p><i class="bi bi-geo-alt m-2"></i>R. Scooby Doo, 5 - Copacabana do Sul - Rio de Janeiro - RJ - CEP: 22000-000</p>
          </div>
        </div>
        <div class="col col-xs-12 text-center">
          <h5>Redes Sociais</h5>
          <div class="social-icons d-flex justify-content-evenly">
            <a href="https://www.facebook.com/?locale=pt_BR"><i class="bi-lg bi-facebook"></i></a>
            <a href="https://twitter.com/i/flow/login?redirect_after_login=%2Fhome"><i class="bi bi-twitter"></i></a>
            <a href="#"><i class="bi bi-instagram"></i></a>
            <a href="#"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>
      </div>
      <div class="d-flex align-items-end row">
        <div class="mt-1 text-center">
          <p class="small">© 2023 Pet's Home. Todos os direitos reservados.</p>
      </div>
    </div>
    </div>
    {% block footer %}
    {% endblock %}
  </footer>
</body>
</html>

base/templates/nav.html
{% load static %}
{% block content %}
<header>
  <nav class="navbar col-12 navbar-expand-lg responsive-navbar-nav">
      <div class="container-fluid col-11 m-auto">
          <a href="{% url 'inicio' %}">
          <img class="img-logo" src="{% static 'images/logo-petsh.svg' %}" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Início</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/adocao">Adoção</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/como-ajudar">Como Ajudar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/sobre-nos">Sobre Nós</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/blog">Blog</a>
            </li>
          </ul>
          <form class="d-flex" action="{% url 'busca_site' %}" method="get">
            <input class="pesquisar-form form-control me-2" type="search" name="q" placeholder="Pesquisar" aria-label="Pesquisar">
            <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
          </form>
        </div>
      </div>
    </nav>
</header>
{% endblock %}